config/routes.rb
Rails.application.routes.draw do

# 设定下述路由后，得到的URL地址应该是类似/users/1/following 和 /users/1/followers这种形式，因为这两个页面都是用来显示数据的，我们用了get方法，指定这两个地址响应的是GET请求
# 路由设置中使用的member方法作用是，设置这两个动作对应的URL地址中应该包含用户的id.类似的，我们还可以使用collection方法，但URL中就没要用户id了
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only:[:new, :create, :destroy]
  resources :microposts, only:[:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root to: 'static_pages#home'
  match '/signup', to: 'users#new', 			via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', 	via: 'delete'
  match '/bdel', to: 'users#destroy_multiple',   via: 'delete'
  match '/bdel', to: 'users#bdel',   via: 'get'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
<nav> <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
</ul> </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "sample app", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Help", help_path %></li>
					<% if signed_in? %>
						<li><%= link_to "Users", users_path %></li>
						<li class="dropdown" id="fat-menu">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">

								<%= current_user.name %> <b class="caret"></b>
							</a>

							<ul class="dropdown-menu">

								<li><%= link_to "Profile", current_user %></li>
								<li><%= link_to "Settings", edit_user_path(current_user) %></li>
								<li class="divider"></li>
								<li>

									<%= link_to "Sign out", signout_path, method: "delete" %>
								</li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to "Sign in", signin_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby on Rails Tutorial Sample App | <%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
  	<div class="container">
      <% flash.each do |key,value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>  
      <% end -%>
    	<%= yield %>
    	<%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
  	</div>
  </body>
</html>